/*
Deployment script for Empty

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Empty"
:setvar DefaultFilePrefix "Empty"
:setvar DefaultDataPath "C:\Users\Mark\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\ProjectsV12\"
:setvar DefaultLogPath "C:\Users\Mark\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\ProjectsV12\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[Item]...';


GO
CREATE TABLE [dbo].[Item] (
    [Id]        INT          IDENTITY (1, 1) NOT NULL,
    [Name]      VARCHAR (50) NOT NULL,
    [PictureId] INT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ItemVendorXref]...';


GO
CREATE TABLE [dbo].[ItemVendorXref] (
    [Id]       INT IDENTITY (1, 1) NOT NULL,
    [ItemId]   INT NOT NULL,
    [VendorId] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [AK_ItemVendorXref_ItemVendor] UNIQUE NONCLUSTERED ([ItemId] ASC, [VendorId] ASC)
);


GO
PRINT N'Creating [dbo].[Picture]...';


GO
CREATE TABLE [dbo].[Picture] (
    [Id]             INT             IDENTITY (1, 1) NOT NULL,
    [PictureContent] VARBINARY (MAX) NULL,
    [Junk]           VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ShoppingEvent]...';


GO
CREATE TABLE [dbo].[ShoppingEvent] (
    [Id]           INT      IDENTITY (1, 1) NOT NULL,
    [VendorId]     INT      NULL,
    [ShoppingDate] DATETIME NOT NULL,
    [DoneShopping] BIT      NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ShoppingItem]...';


GO
CREATE TABLE [dbo].[ShoppingItem] (
    [Id]              INT IDENTITY (1, 1) NOT NULL,
    [ItemId]          INT NOT NULL,
    [ShoppingEventId] INT NOT NULL,
    [Quantity]        INT NOT NULL,
    [IsPurchased]     BIT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Vendor]...';


GO
CREATE TABLE [dbo].[Vendor] (
    [Id]   INT          IDENTITY (1, 1) NOT NULL,
    [Name] VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[ShoppingEvent]...';


GO
ALTER TABLE [dbo].[ShoppingEvent]
    ADD DEFAULT ((0)) FOR [DoneShopping];


GO
PRINT N'Creating unnamed constraint on [dbo].[ShoppingItem]...';


GO
ALTER TABLE [dbo].[ShoppingItem]
    ADD DEFAULT ((0)) FOR [Quantity];


GO
PRINT N'Creating unnamed constraint on [dbo].[ShoppingItem]...';


GO
ALTER TABLE [dbo].[ShoppingItem]
    ADD DEFAULT ((0)) FOR [IsPurchased];


GO
PRINT N'Creating [dbo].[FK_Item_ToPicture]...';


GO
ALTER TABLE [dbo].[Item] WITH NOCHECK
    ADD CONSTRAINT [FK_Item_ToPicture] FOREIGN KEY ([PictureId]) REFERENCES [dbo].[Picture] ([Id]);


GO
PRINT N'Creating [dbo].[FK_ItemVendorXref_ToItem]...';


GO
ALTER TABLE [dbo].[ItemVendorXref] WITH NOCHECK
    ADD CONSTRAINT [FK_ItemVendorXref_ToItem] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[Item] ([Id]);


GO
PRINT N'Creating [dbo].[FK_ItemVendorXref_ToVendor]...';


GO
ALTER TABLE [dbo].[ItemVendorXref] WITH NOCHECK
    ADD CONSTRAINT [FK_ItemVendorXref_ToVendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id]);


GO
PRINT N'Creating [dbo].[FK_ShoppingEvent_ToVendor]...';


GO
ALTER TABLE [dbo].[ShoppingEvent] WITH NOCHECK
    ADD CONSTRAINT [FK_ShoppingEvent_ToVendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([Id]);


GO
PRINT N'Creating [dbo].[FK_ShoppingItem_ToItem]...';


GO
ALTER TABLE [dbo].[ShoppingItem] WITH NOCHECK
    ADD CONSTRAINT [FK_ShoppingItem_ToItem] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[Item] ([Id]);


GO
PRINT N'Creating [dbo].[FK_ShoppingItem_ToShoppingEvent]...';


GO
ALTER TABLE [dbo].[ShoppingItem] WITH NOCHECK
    ADD CONSTRAINT [FK_ShoppingItem_ToShoppingEvent] FOREIGN KEY ([ShoppingEventId]) REFERENCES [dbo].[ShoppingEvent] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Item] WITH CHECK CHECK CONSTRAINT [FK_Item_ToPicture];

ALTER TABLE [dbo].[ItemVendorXref] WITH CHECK CHECK CONSTRAINT [FK_ItemVendorXref_ToItem];

ALTER TABLE [dbo].[ItemVendorXref] WITH CHECK CHECK CONSTRAINT [FK_ItemVendorXref_ToVendor];

ALTER TABLE [dbo].[ShoppingEvent] WITH CHECK CHECK CONSTRAINT [FK_ShoppingEvent_ToVendor];

ALTER TABLE [dbo].[ShoppingItem] WITH CHECK CHECK CONSTRAINT [FK_ShoppingItem_ToItem];

ALTER TABLE [dbo].[ShoppingItem] WITH CHECK CHECK CONSTRAINT [FK_ShoppingItem_ToShoppingEvent];


GO
PRINT N'Update complete.';


GO
