//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingList.Application.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemVendorXref = new HashSet<ItemVendorXref>();
            this.ShoppingItem = new HashSet<ShoppingItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual ICollection<ItemVendorXref> ItemVendorXref { get; set; }
        public virtual ICollection<ShoppingItem> ShoppingItem { get; set; }
    }
}
