//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingList.Application.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.Item = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public byte[] PictureContent { get; set; }
        public string Junk { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
    }
}
