//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingList.Application.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingItem
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int ShoppingEventId { get; set; }
        public int Quantity { get; set; }
        public bool IsPurchased { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ShoppingEvent ShoppingEvent { get; set; }
    }
}
