//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingList.Application.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoppingListDbContext : DbContext
    {
        public ShoppingListDbContext()
            : base("name=ShoppingListDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<ItemVendorXref> ItemVendorXref { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<ShoppingEvent> ShoppingEvent { get; set; }
        public virtual DbSet<ShoppingItem> ShoppingItem { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
    }
}
